install operagtor with adb

diff --git a/.github/workflows/create-branch-clone-db.yaml b/.github/workflows/create-branch-clone-db.yaml
--- a/.github/workflows/create-branch-clone-db.yaml
+++ b/.github/workflows/create-branch-clone-db.yaml
@@ -78,40 +78,40 @@ jobs:
           commit_user_email: "actions@github.com"
           
           
-      - name: Create Autonomous Database from Clone and Upload OCID
-        run: |
-          # Configuration Variables for creating the clone
-          SOURCE_DB_OCID="ocid1.autonomousdatabase.oc1.ap-mumbai-1.anrg6ljrobogfhqajjp7nk74dr3bputn3aa646uistr5xiyxwu5tkh3octuq"
-          CLONE_TYPE="FULL"
-          CLONE_DB_DISPLAY_NAME="Test Clone CICD QA"
-          CLONE_DB_NAME="TestCloneAutomateCICDQA"
-          COMPARTMENT_OCID="ocid1.compartment.oc1..aaaaaaaavkerdgzd55avjsnomocb2ttxb4j4j7gecxwdfwtstwb2iyowtfba"
-          ADMIN_PASSWORD="Igdefault@123"
-          COMPUTE_MODEL="ECPU"
-          COMPUTE_COUNT=2
-          DB_WORKLOAD="OLTP"
+      # - name: Create Autonomous Database from Clone and Upload OCID
+      #   run: |
+      #     # Configuration Variables for creating the clone
+      #     SOURCE_DB_OCID="ocid1.autonomousdatabase.oc1.ap-mumbai-1.anrg6ljrobogfhqajjp7nk74dr3bputn3aa646uistr5xiyxwu5tkh3octuq"
+      #     CLONE_TYPE="FULL"
+      #     CLONE_DB_DISPLAY_NAME="Test Clone CICD QA"
+      #     CLONE_DB_NAME="TestCloneAutomateCICDQA"
+      #     COMPARTMENT_OCID="ocid1.compartment.oc1..aaaaaaaavkerdgzd55avjsnomocb2ttxb4j4j7gecxwdfwtstwb2iyowtfba"
+      #     ADMIN_PASSWORD="Igdefault@123"
+      #     COMPUTE_MODEL="ECPU"
+      #     COMPUTE_COUNT=2
+      #     DB_WORKLOAD="OLTP"
 
-          # Create Autonomous Database from Clone
-          echo "Creating Autonomous Database from Clone..."
-          CREATE_RESPONSE=$(oci db autonomous-database create-from-clone \
-                              --clone-type "$CLONE_TYPE" \
-                              --compartment-id "$COMPARTMENT_OCID" \
-                              --source-id "$SOURCE_DB_OCID" \
-                              --display-name "$CLONE_DB_DISPLAY_NAME" \
-                              --db-name "$CLONE_DB_NAME" \
-                              --wait-for-state AVAILABLE \
-                              --admin-password "$ADMIN_PASSWORD" \
-                              --data-storage-size-in-tbs 1 \
-                              --compute-model "$COMPUTE_MODEL" \
-                              --compute-count "$COMPUTE_COUNT" \
-                              --db-workload "$DB_WORKLOAD")
+      #     # Create Autonomous Database from Clone
+      #     echo "Creating Autonomous Database from Clone..."
+      #     CREATE_RESPONSE=$(oci db autonomous-database create-from-clone \
+      #                         --clone-type "$CLONE_TYPE" \
+      #                         --compartment-id "$COMPARTMENT_OCID" \
+      #                         --source-id "$SOURCE_DB_OCID" \
+      #                         --display-name "$CLONE_DB_DISPLAY_NAME" \
+      #                         --db-name "$CLONE_DB_NAME" \
+      #                         --wait-for-state AVAILABLE \
+      #                         --admin-password "$ADMIN_PASSWORD" \
+      #                         --data-storage-size-in-tbs 1 \
+      #                         --compute-model "$COMPUTE_MODEL" \
+      #                         --compute-count "$COMPUTE_COUNT" \
+      #                         --db-workload "$DB_WORKLOAD")
 
-          if [ -z "$CREATE_RESPONSE" ]; then
-              echo "Failed to create the Autonomous Database from Clone."
-              exit 1
-          else
-              CLONED_DB_OCID=$(echo "$CREATE_RESPONSE" | jq -r '.data.id')
-              echo "Successfully created the Autonomous Database from Clone. OCID: $CLONED_DB_OCID"
+      #     if [ -z "$CREATE_RESPONSE" ]; then
+      #         echo "Failed to create the Autonomous Database from Clone."
+      #         exit 1
+      #     else
+      #         CLONED_DB_OCID=$(echo "$CREATE_RESPONSE" | jq -r '.data.id')
+      #         echo "Successfully created the Autonomous Database from Clone. OCID: $CLONED_DB_OCID"
               
               # Uploading the CLONED_DB_OCID to OCI Object Storage
               echo "Uploading CLONED_DB_OCID to OCI Object Storage..."
@@ -123,3 +123,13 @@ jobs:
                 --force
               echo "Upload successful."
           fi # This closes the if statement
+
+      - name: Update YAML file
+        run: |
+          CLONED_DB_OCID=ocid1.autonomousdatabase.oc1.ap-mumbai-1.anrg6ljrobogfhqawq6nbd3k52n5x7sa4zw322y2qrs5j2q4io3d22ekuazq
+          sed -i "s|<existing_ADB_OCID>|$CLONED_DB_OCID|g" integrate-operator-with-db.yaml
+          sed -i "s|<base64_encoded_password_here>|Igdefault@123|g" integrate-operator-with-db.yaml
+          sed -i "s|<base64_encoded_private_key_here>|$OCI_CLI_KEY_CONTENT|g" integrate-operator-with-db.yaml
+
+      - name: Display updated YAML file
+        run: cat your_yaml_file.yaml
